const palette = require('../mui/palette')
const typography = require('../mui/typography')
const { fade } = require('@material-ui/core/styles/colorManipulator')

module.exports = {
  root: {
    display: 'flex',
    width: '100%',
    position: 'relative',
    '&:before': {
      content: '""',
      position: 'fixed',
      backgroundColor: 'rgba(0, 0, 0, 0)',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      pointerEvents: 'none',
      transition: 'all 0.2s ease',
    },
    '&.focused': {
      '&& input': {
        position: 'relative',
        zIndex: 1,
        transform: 'scale(1.03)',
        transition: 'all 0.2s ease',
      },
      '&& button': {
        transform: 'scale(1.03)',
        transition: 'all 0.2s ease',
      },
      '&:before': {
        backgroundColor: 'rgba(0, 0, 0, 0.3)',
        transition: 'all 0.3s ease',
      },
      '&& .results.visible': {
        maxHeight: 240,
        transition: 'all 0.2s ease 0.2s',
      },
      '&& .no-results.visible': {
        maxHeight: 60,
        transition: 'all 0.2s ease 0.2s',
      },
    },
    '& .results': {
      position: 'absolute',
      left: -4,
      right: 0,
      top: 40,
      background: palette.background.paper,
      width: 'calc(100% + 4px)',
      transition: 'all 0.2s ease',
      maxHeight: 0,
      overflow: 'hidden',
      zIndex: 1,
      '& .MuiTypography-h5': {
        padding: '12px 8px',
        display: 'block',
        textDecoration: 'none',
      },
      '& .MuiTypography-h5.results-label': {
        borderBottomWidth: 1,
        borderBottomColor: palette.tertiary.main,
        borderBottomStyle: 'solid',
        color: palette.tertiary.main,
        margin: '0 0 4px 8px',
        width: 'calc(100% - 32px)',
        padding: '4px 0 8px',
      },
    },
    '& .no-results': {
      position: 'absolute',
      left: -4,
      right: 0,
      top: 40,
      background: palette.background.paper,
      width: 'calc(100% + 4px)',
      transition: 'all 0.2s ease',
      maxHeight: 0,
      overflow: 'hidden',
      zIndex: 1,
      '& .MuiTypography-h5': {
        padding: '12px 8px',
        display: 'block',
        textDecoration: 'none',
      },
    },
  },
  input: {
    ...typography.h6,
    backgroundColor: palette.background.dark,
    border: '1px solid',
    borderColor: palette.tertiary.main,
    borderBottomLeftRadius: 4,
    borderRight: 0,
    borderTopLeftRadius: 4,
    flex: 1,
    padding: 8,
    outline: 0,
    paddingLeft: 12,
    transition: 'all 0.2s ease 0.2s',
    '&::placeholder': {
      ...typography.h6,
    },
  },
  button: {
    backgroundColor: palette.action.main,
    border: '1px solid',
    borderColor: palette.tertiary.main,
    borderRadius: 4,
    borderBottomLeftRadius: 0,
    borderLeft: 0,
    borderTopLeftRadius: 0,
    boxShadow: 'none',
    color: palette.background.default,
    height: '100%',
    padding: 4,
    minWidth: 32,
    minHeight: 35,
    transition: 'all 0.2s ease 0.2s',
    zIndex: 2,
    '&:hover': {
      backgroundColor: fade(palette.action.main, 0.8),
    },
  },
}
