export const defaultContent = [
  {
    label: 'Page Title',
    name: 'title',
    type: 'title',
    value: '',
  },
  {
    label: 'Page Description',
    type: 'meta',
    name: 'description',
    multiline: true,
    value: '',
  },
  {
    label: 'Open Graph Type',
    type: 'meta',
    name: 'og:type',
    property: 'og:type',
    value: '',
  },
  {
    label: 'Open Graph Title',
    type: 'meta',
    name: 'og:title',
    property: 'og:title',
    value: '',
  },
  {
    label: 'Open Graph Description',
    type: 'meta',
    name: 'og:description',
    property: 'og:description',
    multiline: true,
    value: '',
  },
  {
    label: 'Open Graph Image',
    type: 'meta',
    name: 'og:image',
    property: 'og:image',
    value: '',
  },
  {
    label: 'Structured Data',
    type: 'script',
    name: 'structuredData',
    multiline: true,
    value: '{}',
  },
]
